### ISSUE TITLE
两个不同的套件，第一个套件的应用发送消息正常，第二个套件下的应用就报一下错误

### ISSUE THREAD

**Issue by zqj** [lanrion/qy_wechat#12]
MultiXml::ParseError (Start tag expected, '<' not found):
  multi_xml (0.5.5) lib/multi_xml/parsers/nokogiri.rb:15:in `parse'
  multi_xml (0.5.5) lib/multi_xml.rb:138:in `parse'
  /home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat-31d0c92ad14e/app/controllers/qy_wechat/qy_wechat_controller.rb:32:in `setup_wechat_message'
  activesupport (4.1.8) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.1.8) lib/active_support/callbacks.rb:143:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  simple_captcha2 (0.3.2) lib/simple_captcha/middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'

**Comment by zqj** [comment]
QyAuthAgent Load (0.3ms)  SELECT  `qy_auth_agents`.* FROM `qy_auth_agents`  WHERE `qy_auth_agents`.`qy_secret_key` = 'agent_wxfac088bb438a96d7' LIMIT 1
DEBUG WECHAT MESSAGE: <xml><ToUserName><![CDATA[wxfac088bb438a96d7]]></ToUserName>
<Encrypt><![CDATA[8llqFHlYZKwV31qQpeZKTkLgQmC9Y2q5Q80e7zGvSsvwAhq5LiTahIXmej00LzugnsjeO/py208cscOG52ZfcrtWUud8y1W+ieKT4PHu1rjtP54an8Dl9JDN89CCl53mXmtr7x0t5bcNTXyuhceHOcUwvBqNSvL+w+8THP4QwlnJcyGxKhVr1v2nPEoZEc/DVr8UByWGWR9ejDZWGVzG0Gz4uUEfbBxYaulFbGZQwOsNl49gG2rNtniaIuRat8orhuZr3O8ebh050sEwS1VYDJt0lnmkgcMq4GkhAmxWCtlZPsddHeA8Llx3Qhowmvfhno1MkK9/z5vB94vX/YSadm82BWsxOp+WKPPYXx2nSHtCUf4d0GtHRnIc6X6MIfjYOv+foX9IVBwOKliEwSnEcqodEiMjfCc5ddHk0SJM79BghP9S9kA0U3bv02H+AgFuYf4T4ioPoHCRZHs2FLKy6kgmieBglRSMG/NFHfF9KnG8Zn8aAASb8cTAk5DuHON5NciTry6vhFgGzxZ1WXhqhT5mJ+174Bvfwc5o8AewlYNT5DRm6yJGiTALWfQOku6UZkA306yvWaXRb+PSgdks3s3I31KtStg14Y4DlPOT5r3WKtJdeoW90IPL42LKrfR575NAEmMTnMq5kvZLuXSqJK9N4A29RDVxg2CbuiS7wJ5I+D+v67IQp2I9tj0u/FK0ir9q5SmgZlN3dCrGN3gm4K+LblzcwA/DG9gPutO2MXp+dRxJE+pqxrTQZgRM66y6]]></Encrypt>
<AgentID><![CDATA[43]]></AgentID>
</xml>
  QySuite Load (0.2ms)  SELECT  `qy_suites`.* FROM `qy_suites`  WHERE `qy_suites`.`suite_id` = 'tj248c47c1714be67c' LIMIT 1
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat-3f339d806d79/lib/qy_wechat/helpers/prpcrypt.rb:20 Failure because corpid != from_corpid
Completed 500 Internal Server Error in 4ms
   (0.1ms)  COMMIT

MultiXml::ParseError (Start tag expected, '<' not found):
  multi_xml (0.5.5) lib/multi_xml/parsers/nokogiri.rb:15:in `parse'
  multi_xml (0.5.5) lib/multi_xml.rb:138:in `parse'
  /home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat-3f339d806d79/app/controllers/qy_wechat/qy_wechat_controller.rb:33:in `setup_wechat_message'
  activesupport (4.1.8) lib/active_support/callbacks.rb:424:in `block in make_lambda'

**Comment by zqj** [comment]
encoding_aes_key: 1nvFPSVnuVMuaBs2RtJJqYX5w37UiOszgmqBstBnzta, qy_token: VCH8cv, corp_id: wxfac088bb438a96d7
DEBUG WECHAT MESSAGE: <xml><ToUserName><![CDATA[wxfac088bb438a96d7]]></ToUserName>
<Encrypt><![CDATA[5Vru0Qy/Kim5OaDLXZ8Fq1MBE3vgblJDyFxAIU4q32NxMSXb42Iri4cD9iNTP306/6gA7U+k76Z8A7vZPPXCYd5YaI5mC9IJ1gjEYM2o7Ay5VmhKk1Qe4Veu3QUFQ1muNdw830ZbX9rvtvrqzoyq18cVBkezx9Ak/uAer80zSXlUQbGRJQ8i/XR70orJGUOAx/Mjs9cHsGd8jaKCbWSVTz5YCn++87w4ep4794zMX9V5+U75ztw1ll0Q0/VoUkxR0pDwLvRxZkVAwueM6AJ2ozYqlXNZcygodDI60GMbjD8gHNeW3d+gZ7W//si+54FHK5xCentCTj3oz3FJoRQegwdzLXpbi6wW/HldXhPUNJjBJihWwqFDiiTwjGkohMoD6YzFcgVr21KIYTLfLi1W+VNty7nWXjwPjZAaL+EMFDESbnNLLVmGwF1YkJwntkEq3Q3CzAIFR45e/UMXGCVXFGwWA9GHIblyw9XvoL3shfp/Jqs5mhK/uE8g9M6BetGzjlFgHd8v+ek/TCBH/Kyor43AJ3MyokeDaoi9bTqz+kaw88DvQh3gE0jY+uZd5SHu0QPpkX7SF0gSW+mjH9F3d2SALqsCSDvSDQkEpb6RjslxeDi31+n7pqIRD3ZG+KIUaRUbPeLPe+53tGKb4DE0XfU8pjYIvTRjCb6qYMh1U0FWKbSQNzHDNgDgwe7Y4Ys5ezUk6otYwDYwEbc1KCUlyNguy8OnhDahwd/gZjMIfzj+nh/R0/n1hyNmJi3EuGW9]]></Encrypt>
<AgentID><![CDATA[43]]></AgentID>
</xml>
/home/deploy/xiaoshouke/shared/bundle/ruby/2.1.0/bundler/gems/qy_wechat-8905fc0c911d/lib/qy_wechat/helpers/prpcrypt.rb:20 Failure because wxfac088bb438a96d7 != 
DECRYPT WECHAT MESSAGE: ???9O??C?$?2R??9ˬ???-E?[?+h??i??3>(??W?%g1QU5ʔ??j??oA???,?>?a?w&???????{?y????ʀ<???W?_࢝???
                                                                                                                  h7???2,???????????ܟ?}?k??A,??+"4H*?	Z?M???AE???7?
&?ff?^1-??ba䛨?H5s???nشh?G?,???e?%r?????o???IE
                         ?!3??V?>???l??3????[?`k?A?G?oE??????#?{?t?Ȗ??=??|3???q6???:p?]?<_0+g??_,???˰AӧT??a?
?8(?{???<B???????X?̉???c?ϩ+1??ԩYI?Q)?RB????٬K4+%ĺ?ƌՋ#?L?ʐ1??s͢/l?Χ:?????Y?M9?i=??!?B4??,??yh?Y??
                                                                                              ?????q??9?ۙ??$?^՝?Bsѡ?Q`?O?@???[t??tn&¦|r??x=,?hb^3???f?<H÷?4ۣ?cZ?"??
Completed 500 Internal Server Error in 4ms

MultiXml::ParseError (Start tag expected, '<' not found):

**Comment by zqj** [comment]
encoding_aes_key: 1nvFPSVnuVMuaBs2RtJJqYX5w37UiOszgmqBstBnzta, qy_token: VCH8cv, corp_id: wxfac088bb438a96d7
DEBUG WECHAT MESSAGE: <xml><ToUserName><![CDATA[wxfac088bb438a96d7]]></ToUserName>
<Encrypt><![CDATA[v/Bq855ur4nOzygu+4Rk/kC2P6kGM1o8v58Kh/QoWN+a5X87uV1bmoy2+Ge0VEcC+An4z219W7VN8IDVKG72gWMgeumqcKkwxFhuZR7cMYhIe5dfoGsslposim3N3oLsCP1yxiYNmTeItZluTZM2a+l7tdOL8alvYcztPqqsiUn6++ElOCH8eg5wpX0uyYg+5O//H5ZUDSifnK7TOQqZSiSJlqMG46jX2/RamkvXNLxHegWPRPun0CVRCVrkpGU432mUi9utNnQLc9llzmCN0HZot1YJqUG4aUvunwJ9puYn7zdr3T3fe0KNW19ms4AUTSFPzta/wob3MS6NjAoRwgVIwkfp+HeUsrJf4EIxNykHzzjAgQ40xTWXuenRqfHZq6eCSZG98vxaeZNwXof2jJGFon2VVKwGb7FVVTIYEQ7Xq9HKaPtWeDnAW758Wc8CmoS7Io4OV5JtfoBbhLtmmh1f1oH4E6XRufOiWREc4n3WuuvzcWiboQEPTJbbyMvrcZdVy8Zc/4Iug+cmTBwvE83K7I4S4MzAoOMFJqpg7lZg3THyUt5t2/Wnp+C0EuhV4mq9U1Vzm9YLDwoVNBO23TmjA4IhaxJY7EieiCsyi7T9Jue0RdpBD5XKSbsE9AJ5jYYC38QcuL8Laj4qFUn/px1TbOwdwvyq7F7wjQvC560Zu8Tivh4OHE9EONKAL2IiPWP95o2/Ju4F3XfGTMuDiSxlhb0++dksV7Ar8W2mR5foSacZvICHFgOHBD74KEwG]]></Encrypt>
<AgentID><![CDATA[9]]></AgentID>
</xml>
   (0.2ms)  COMMIT
DECRYPT WECHAT MESSAGE: <xml><ToUserName><![CDATA[wxfac088bb438a96d7]]></ToUserName>
<FromUserName><![CDATA[mooogo]]></FromUserName>
<CreateTime>1429595815</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<AgentID>9</AgentID>
<Event><![CDATA[view]]></Event>
<EventKey><![CDATA[https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxfac088bb438a96d7&redirect_uri=http%3A%2F%2Fcrm.xiaoshouke.cn%2Fapp_index%2Fapply_leaves%3Fagent_id%3D9%26user_id%3D2&response_type=code&scope=snsapi_base&state=xiaoshoukecrm#wechat_redirect]]></EventKey>
</xml>

**Comment by lanrion** [comment]
确保 配置正确。
